[package]
name = "aoc2023_by_luk6xff"
version = "0.1.0"
authors = ["luk6xff <lukasz.uszko@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

